
name: "Clean'em all"

on:
  workflow_dispatch:

env:
  # Terraform
  # TF_VERSION: 1.0.5
  TF_LOG_PATH: ${{ secrets.TF_LOG_PATH }}

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
 
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Terraform Destroy
        run: | 
          terraform init
          terraform destroy -auto-approve